---
certs:
  secretName: vault-tls

server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "false"

  standalone:
    enabled: true

  dataStorage:
    storageClass: openebs-hostpath
