---
loki:
  serviceScheme: https

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - host: loki.test.local
      paths: ["/"]
    tls:
    - secretName: loki-tls
      hosts:
      - loki.test.local

  persistence:
    enabled: true
    storageClass: openebs-hostpath

  podAnnotations:
    "consul.hashicorp.com/connect-inject": "true"
