---
buckets:
- name: gitlab
  policy: none
  purge: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - minio.test.local
  tls:
  - secretName: minio-tls
    hosts:
    - minio.test.local

resources:
  requests:
    memory: 256Mi

persistence:
  enabled: true
  storageClass: minio-data
  size: 10Gi

podAnnotations:
  consul.hashicorp.com/connect-inject: "true"
