---
global:
  domain: consul
  datacenter: dc1

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  storage: 10Gi
  storageClass: openebs-hostpath

client:
  enabled: true
  grpc: true

dns:
  enabled: true
  clusterIP: 10.99.247.81

#ingressGateways:
#  enabled: true
#  defaults:
#    replicas: 1

ui:
  enabled: true

connectInject:
  enabled: true
  imageEnvoy: envoyproxy/envoy:v1.13.1
