---
grafana.ini:
  server:
    domain: grafana.test.local

ingress:
  enabled: true
  path: /
  hosts:
    - grafana.test.local
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.test.local

persistence:
  enabled: true
  storageClassName: grafana-data

podAnnotations:
  consul.hashicorp.com/connect-inject: "true"
  consul.hashicorp.com/connect-service-upstreams: "loki:9000"
