---
env:
  LDAP_DOMAIN: test.local
  LDAP_ORGANISATION: Test Infrastructure

tls:
  enabled: true
  secret: openldap-tls

persistence:
  enabled: true
  storageClass: openebs-hostpath

logLevel: trace
