---
global:
  imageEnvoy: envoyproxy/envoy:v1.13.1

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  storage: 10Gi
  storageClass: openebs-hostpath

client:
  enabled: true
  grpc: true
  updateStrategy: |
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate

dns:
  enabled: true

ui:
  enabled: true

connectInject:
  enabled: true

ingressGateways:
  enabled: true
  defaults:
    replicas: 1

syncCatalog:
  enabled: true
  toConsul: true
  default: true
