# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    consul = {
      source = "hashicorp/consul"
      version = "~> 2.10.1"
    }

    helm = {
      source  = "hashicorp/helm"
      version = "~> 1.3.2"
    }

    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 1.13.3"
    }

    local = {
      source  = "hashicorp/local"
      version = "~> 2.0.0"
    }

    random = {
      source  = "hashicorp/random"
      version = "~> 3.0.0"
    }

    tls = {
      source  = "hashicorp/tls"
      version = "~> 3.0.0"
    }

    vault = {
      source = "hashicorp/vault"
      version = "~> 2.15.0"
    }
  }
}

provider "consul" {
  # FIXME
  address    = "127.0.0.1:8500"
  datacenter = "dc1"
}

provider "helm" {
  kubernetes {
    config_context = "docker-desktop"
  }
}

provider "kubernetes" {
  config_context = "docker-desktop"
}

provider "kubernetes-alpha" {
  config_path    = "~/.kube/config"
  config_context = "docker-desktop"
}

provider "vault" {
  address         = "https://vault.test.local:30443"
  skip_tls_verify = true
}    
