---
global:
  edition: ce
  hosts:
    domain: test.local
    https: true

  psql:
    # TODO: Connect to PostgreSQL through Consul Connect
    # host: localhost
    host: postgresql.postgresql.svc.cluster.local
    port: 5432
    username: gitlab
    password:
      secret: gitlab-postgresql
      key: password
    database: gitlab

  registry:
    bucket: gitlab-registry

  appConfig:
    lfs:
      bucket: gitlab-lfs
      connection:
        secret: rails-s3-minio
        key: connection
    artifacts:
      bucket: gitlab-artifacts
      connection:
        secret: rails-s3-minio
        key: connection
    uploads:
      bucket: gitlab-uploads
      connection:
        secret: rails-s3-minio
        key: connection
    packages:
      bucket: gitlab-packages
      connection:
        secret: rails-s3-minio
        key: connection
    backups:
      bucket: gitlab-backup
      tmpBucket: gitlab-tmp

  ingress:
    configureCertmanager: false
    class: nginx
    tls:
      secretName: gitlab-tls

  grafana:
    enabled: false

  minio:
    enabled: false

certmanager:
  install: false

gitlab:
  gitaly:
    persistence:
      enabled: true
      storageClass: gitlab-gitaly-data
      size: 10Gi

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

  sidekiq:
    annotations:
      consul.hashicorp.com/connect-inject: "true"
      consul.hashicorp.com/connect-service: gitlab-sidekiq
      consul.hashicorp.com/connect-service-upstream: "postgresql:5432"
    minReplicas: 1
    maxReplicas: 1

  task-runner:
    backups:
      objectStorage:
        config:
          secret: s3cmd-config
          key: config

  webservice:
    annotations:
      consul.hashicorp.com/connect-inject: "true"
      consul.hashicorp.com/connect-service: gitlab-webservice
      consul.hashicorp.com/connect-service-upstreams: "postgresql:5432"
    minReplicas: 1
    maxReplicas: 1

nginx-ingress:
  enabled: false

postgresql:
  install: false

prometheus:
  install: false

redis:
  master:
    persistence:
      enabled: true
      storageClass: gitlab-redis-data
      size: 10Gi

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
