---
master:
  limits:
    memory: 384Mi

  jenkinsUrl: 'https://jenkins.test.local:30443'
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.test.local
    path: /
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.test.local

  podAnnotations:
    consul.hashicorp.com/connect-inject: "true"

persistence:
  enabled: true
  storageClass: openebs-hostpath
