---
alertmanager:
  baseURL: https://alertmanager.test.local
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.test.local
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.test.local

  persistentVolume:
    storageClass: openebs-hostpath

  podAnnotations:
    consul.hashicorp.com/connect-inject: "true"

  strategy:
    type: Recreate

pushgateway:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - pushgateway.test.local
    tls:
      - secretName: alertmanager-tls
        hosts:
          - pushgateway.test.local

  persistentVolume:
    storageClass: openebs-hostpath

  podAnnotations:
    consul.hashicorp.com/connect-inject: "true"

  strategy:
    type: Recreate

server:
  baseURL: https://prometheus.test.local
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.test.local
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.test.local

  persistentVolume:
    storageClass: openebs-hostpath

  podAnnotations:
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/connect-service: "prometheus-server"
    consul.hashicorp.com/connect-service-port: "9090"

  strategy:
    type: Recreate
