---
buckets:
  - name: gitlab-artifacts
    policy: none
    purge: false
  - name: gitlab-backup
    policy: none
    purge: false
  - name: gitlab-lfs
    policy: none
    purge: false
  - name: gitlab-packages
    policy: none
    purge: false
  - name: gitlab-registry
    policy: none
    purge: false
  - name: gitlab-tmp
    policy: none
    purge: false
  - name: gitlab-uploads
    policy: none
    purge: false
  - name: velero
    policy: none
    purge: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - minio.test.local
  tls:
    - secretName: minio-tls
      hosts:
        - minio.test.local

resources:
  requests:
    memory: 256Mi

persistence:
  enabled: true
  storageClass: openebs-hostpath
  size: 10Gi

podAnnotations:
  # HashiCorp Consul
  consul.hashicorp.com/connect-inject: "true"
