---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - minio.test.local
  tls:
    - secretName: minio-tls
      hosts:
        - minio.test.local

resources:
  requests:
    memory: 256Mi

persistence:
  enabled: true
  storageClass: openebs-hostpath
  size: 10Gi

podAnnotations:
  # HashiCorp Consul
  consul.hashicorp.com/connect-inject: "true"
